/*
 Equipo #2
 CONTRERAS RODRIGUEZ JANIS ISABEL
 LIRA DOMINGUEZ BRYANT 
 PARRA GONZALEZ DIEGO ALBERTO
 */
package front_end;
/**
 *
 * @author PC
 */

import back_end.Biblioteca;
import back_end.Libro;

public class TestBiblioteca extends javax.swing.JFrame {
    private Biblioteca biblioteca; //Esta es la instancia
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestBiblioteca.class.getName());
    /**
     * Creates new form TestBiblioteca
     */
    public TestBiblioteca() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCrearBiblioteca = new javax.swing.JButton();
        btnMostrarLibros = new javax.swing.JButton();
        btnAgregarLibros = new javax.swing.JButton();
        btnModificarLibros = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        btnMostrarPorIndice = new javax.swing.JButton();
        btnDestruirBiblioteca = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtAutor = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultados = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE GESTIÓN DE BIBLIOTECA");
        jLabel1.setToolTipText("");

        btnCrearBiblioteca.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnCrearBiblioteca.setText("Crear biblioteca");
        btnCrearBiblioteca.addActionListener(this::btnCrearBibliotecaActionPerformed);

        btnMostrarLibros.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnMostrarLibros.setText("Mostrar libros");
        btnMostrarLibros.addActionListener(this::btnMostrarLibrosActionPerformed);

        btnAgregarLibros.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnAgregarLibros.setText("Agregar libro");
        btnAgregarLibros.addActionListener(this::btnAgregarLibrosActionPerformed);

        btnModificarLibros.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnModificarLibros.setText("Modificar libro");
        btnModificarLibros.addActionListener(this::btnModificarLibrosActionPerformed);

        btnEliminarLibro.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnEliminarLibro.setText("Eliminar libro");
        btnEliminarLibro.addActionListener(this::btnEliminarLibroActionPerformed);

        btnMostrarPorIndice.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnMostrarPorIndice.setText("Mostrar por índice");
        btnMostrarPorIndice.addActionListener(this::btnMostrarPorIndiceActionPerformed);

        btnDestruirBiblioteca.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnDestruirBiblioteca.setText("Destruir biblioteca");
        btnDestruirBiblioteca.addActionListener(this::btnDestruirBibliotecaActionPerformed);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarPorIndice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCrearBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDestruirBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCrearBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMostrarPorIndice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDestruirBiblioteca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Autor:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Año:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Título:");

        txtIndice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtAño.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Índice:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(txtAutor))
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txaResultados.setEditable(false);
        txaResultados.setColumns(20);
        txaResultados.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txaResultados.setRows(5);
        txaResultados.setText("===========================================================\n        ¡BIENVENIDO AL SISTEMA DE GESTIÓN DE BIBLIOTECA!              \n===========================================================\n\nPASOS PARA COMENZAR:\n1. Escriba la capacidad máxima deseada en el campo 'Índice'.\n2. Presione el botón 'Crear biblioteca'.\n\nOPERACIONES DISPONIBLES:\n• Agregar / Modificar: Llene Título, Autor, Año e Índice.\n• Eliminar / Mostrar: Llene únicamente el campo 'Índice'.\n• Mostrar Libros: Muestra el estado actual de los estantes.\n• Destruir Biblioteca: Borra la biblioteca activa.\n===========================================================");
        txaResultados.setEnabled(false);
        jScrollPane1.setViewportView(txaResultados);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Resultados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 615, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Equipo #2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Botones
    private void limpiarCampos() { //Esto pa que se limpie y puedas escribir
        txtTitulo.setText(""); // y porque me confundo menos jajjja
        txtAutor.setText("");
        txtAño.setText("");
        txtIndice.setText("");
    }
    private void btnCrearBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearBibliotecaActionPerformed
       String strCapacidad = txtIndice.getText().trim();

    if (strCapacidad.isEmpty()) {
        txaResultados.setText("Error: Ingrese la capacidad deseada en el campo 'Índice'.");
        return;
    }

    try {
        int capacidad = Integer.parseInt(strCapacidad);
        this.biblioteca = new Biblioteca(capacidad);// Instanciamos el objeto
        txaResultados.setText(this.biblioteca.crearBiblioteca(capacidad));// Llamamos al método backend y mostramos el resultado
        limpiarCampos();
    } catch (NumberFormatException e) {
        txaResultados.setText("Error: La capacidad debe ser un número entero válido.");
    }
    }//GEN-LAST:event_btnCrearBibliotecaActionPerformed

    private void btnMostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarLibrosActionPerformed
        if (biblioteca == null) {
            txaResultados.setText("Error: La biblioteca no ha sido creada.");
        } else {
            txaResultados.setText(biblioteca.mostrarLibros());
            limpiarCampos();
        }
    }//GEN-LAST:event_btnMostrarLibrosActionPerformed

    private void btnAgregarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibrosActionPerformed
        if (biblioteca == null) {
            txaResultados.setText("Error: La biblioteca no ha sido creada.");
            return;
        }

        String titulo = txtTitulo.getText().trim();
        String autor = txtAutor.getText().trim();
        String strAnio = txtAño.getText().trim();
        String strIndice = txtIndice.getText().trim();

        if (titulo.isEmpty() || autor.isEmpty() || strAnio.isEmpty() || strIndice.isEmpty()) {
            txaResultados.setText("Error: Todos los campos (Título, Autor, Año e Índice) son obligatorios.");
            return;
        }

        try {
            int anio = Integer.parseInt(strAnio);
            int indice = Integer.parseInt(strIndice);

            Libro libro = new Libro(titulo, autor, anio);
            txaResultados.setText(biblioteca.agregarLibro(libro, indice));
            limpiarCampos();
        } catch (NumberFormatException e) {
            txaResultados.setText("Error: El Año y el Índice deben ser números enteros.");
        }
    }//GEN-LAST:event_btnAgregarLibrosActionPerformed

    private void btnModificarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLibrosActionPerformed
        if (biblioteca == null) {
            txaResultados.setText("Error: La biblioteca no ha sido creada.");
            return;
        }

        String titulo = txtTitulo.getText().trim();
        String autor = txtAutor.getText().trim();
        String strAnio = txtAño.getText().trim();
        String strIndice = txtIndice.getText().trim();

        if (titulo.isEmpty() || autor.isEmpty() || strAnio.isEmpty() || strIndice.isEmpty()) {
            txaResultados.setText("Error: Debe llenar Título, Autor, Año e Índice para modificar un libro.");
            return;
        }

        try {
            int anio = Integer.parseInt(strAnio);
            int indice = Integer.parseInt(strIndice);
            Libro libroModificado = new Libro(titulo, autor, anio);
            txaResultados.setText(biblioteca.modificarLibro(indice, libroModificado));
            limpiarCampos();
        } catch (NumberFormatException e) {
            txaResultados.setText("Error: El Año y el Índice deben ser números enteros.");
        }
    }//GEN-LAST:event_btnModificarLibrosActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
       if (biblioteca == null) {
            txaResultados.setText("Error: La biblioteca no ha sido creada.");
            return;
        }

        String strIndice = txtIndice.getText();
        if (strIndice.isEmpty()) {
            txaResultados.setText("Error: Debe ingresar la posición (Índice) del libro a eliminar.");
            return;
        }

        try {
            int indice = Integer.parseInt(strIndice);
            txaResultados.setText(biblioteca.eliminarLibro(indice));
            limpiarCampos();
        } catch (NumberFormatException e) {
            txaResultados.setText("Error: El Índice debe ser un número entero.");
        }
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnMostrarPorIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPorIndiceActionPerformed
        if (biblioteca == null) {
            txaResultados.setText("Error: La biblioteca no ha sido creada.");
            return;
        }

        String strIndice = txtIndice.getText();
        if (strIndice.isEmpty()) {
            txaResultados.setText("Error: Debe ingresar el Índice a consultar.");
            return;
        }

        try {
            int indice = Integer.parseInt(strIndice);
            txaResultados.setText(biblioteca.mostrarLibroPorIndice(indice));
            limpiarCampos();
        } catch (NumberFormatException e) {
            txaResultados.setText("Error: El Índice debe ser un número entero.");
        }
    }//GEN-LAST:event_btnMostrarPorIndiceActionPerformed

    private void btnDestruirBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestruirBibliotecaActionPerformed
        if (biblioteca == null) {
            txaResultados.setText("Error: La biblioteca no ha sido creada o ya fue destruida.");
            return;
        }
        txaResultados.setText(biblioteca.destruirBiblioteca());
        biblioteca = null; // Liberar la referencia 
        limpiarCampos();
    }//GEN-LAST:event_btnDestruirBibliotecaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibros;
    private javax.swing.JButton btnCrearBiblioteca;
    private javax.swing.JButton btnDestruirBiblioteca;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnModificarLibros;
    private javax.swing.JButton btnMostrarLibros;
    private javax.swing.JButton btnMostrarPorIndice;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaResultados;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
